// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_LogitechToolkit : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean PrimaryClick
        {
            get
            {
                return SteamVR_Actions.logitechToolkit_PrimaryClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TipClick
        {
            get
            {
                return SteamVR_Actions.logitechToolkit_TipClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripClick
        {
            get
            {
                return SteamVR_Actions.logitechToolkit_GripClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuClick
        {
            get
            {
                return SteamVR_Actions.logitechToolkit_MenuClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadTouch
        {
            get
            {
                return SteamVR_Actions.logitechToolkit_TrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadClick
        {
            get
            {
                return SteamVR_Actions.logitechToolkit_TrackpadClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackpadValue
        {
            get
            {
                return SteamVR_Actions.logitechToolkit_TrackpadValue;
            }
        }
        
        public virtual SteamVR_Action_Single PrimaryPressure
        {
            get
            {
                return SteamVR_Actions.logitechToolkit_PrimaryPressure;
            }
        }
        
        public virtual SteamVR_Action_Single TipPressure
        {
            get
            {
                return SteamVR_Actions.logitechToolkit_TipPressure;
            }
        }
        
        public virtual SteamVR_Action_Single GripPressure
        {
            get
            {
                return SteamVR_Actions.logitechToolkit_GripPressure;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.logitechToolkit_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptics
        {
            get
            {
                return SteamVR_Actions.logitechToolkit_Haptics;
            }
        }
    }
}
